// Created by iWeb 3.0.4 local-build-20190103

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-2,7,11,152),url:'About_Me_files/stroke_11.png'},{rect:new IWRect(-2,-1,11,8),url:'About_Me_files/stroke_12.png'},{rect:new IWRect(9,1,123,6),url:'About_Me_files/stroke_13.png'},{rect:new IWRect(132,1,12,6),url:'About_Me_files/stroke_14.png'},{rect:new IWRect(132,7,12,152),url:'About_Me_files/stroke_15.png'},{rect:new IWRect(-3,-3,0,0),url:null},{rect:new IWRect(-3,-3,0,0),url:null},{rect:new IWRect(1,159,8,1),url:'About_Me_files/stroke_16.png'}],new IWSize(141,157)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,9,16,76),url:'About_Me_files/stroke_6.png'},{rect:new IWRect(-7,-5,21,14),url:'About_Me_files/stroke_7.png'},{rect:new IWRect(14,-2,93,11),url:'About_Me_files/stroke_8.png'},{rect:new IWRect(107,0,1,9),url:'About_Me_files/stroke_9.png'},{rect:new IWRect(-7,-5,0,0),url:null},{rect:new IWRect(-7,-5,0,0),url:null},{rect:new IWRect(-7,-5,0,0),url:null},{rect:new IWRect(2,85,12,1),url:'About_Me_files/stroke_10.png'}],new IWSize(102,80)),stroke_0:new IWStrokeParts([{rect:new IWRect(-4,9,16,117),url:'About_Me_files/stroke.png'},{rect:new IWRect(-5,-3,17,12),url:'About_Me_files/stroke_1.png'},{rect:new IWRect(12,-2,81,11),url:'About_Me_files/stroke_2.png'},{rect:new IWRect(93,1,4,8),url:'About_Me_files/stroke_3.png'},{rect:new IWRect(93,9,4,117),url:'About_Me_files/stroke_4.png'},{rect:new IWRect(-6,-3,0,0),url:null},{rect:new IWRect(-6,-3,0,0),url:null},{rect:new IWRect(0,126,12,1),url:'About_Me_files/stroke_5.png'}],new IWSize(90,121)),stroke_3:new IWStrokeParts([{rect:new IWRect(-2,7,9,245),url:'About_Me_files/stroke_17.png'},{rect:new IWRect(-3,-3,10,10),url:'About_Me_files/stroke_18.png'},{rect:new IWRect(7,-2,136,9),url:'About_Me_files/stroke_19.png'},{rect:new IWRect(143,0,1,7),url:'About_Me_files/stroke_20.png'},{rect:new IWRect(-3,-3,0,0),url:null},{rect:new IWRect(-3,-3,0,0),url:null},{rect:new IWRect(-3,-3,0,0),url:null},{rect:new IWRect(-1,252,8,1),url:'About_Me_files/stroke_21.png'}],new IWSize(141,250)),stroke_4:new IWStrokeParts([{rect:new IWRect(-3,4,12,212),url:'About_Me_files/stroke_22.png'},{rect:new IWRect(-3,-3,12,7),url:'About_Me_files/stroke_23.png'},{rect:new IWRect(9,-3,121,7),url:'About_Me_files/stroke_24.png'},{rect:new IWRect(130,-2,8,6),url:'About_Me_files/stroke_25.png'},{rect:new IWRect(130,4,8,212),url:'About_Me_files/stroke_26.png'},{rect:new IWRect(-3,-3,0,0),url:null},{rect:new IWRect(-3,-3,0,0),url:null},{rect:new IWRect(2,216,7,1),url:'About_Me_files/stroke_27.png'}],new IWSize(134,215))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('About_Me_files/About_MeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');fixAllIEPNGs('Media/transparent.gif');Widget.onload();fixupAllIEPNGBGs();fixupIECSS3Opacity('id8');applyEffects()}
function onPageUnload()
{Widget.onunload();}
